import { useState, useEffect } from 'react';
import '../styles/myorders.css'
import '../styles/searchTab.css'; // from styles folder, import searchTab.css
import { useNavigate } from 'react-router-dom';
import React from 'react';
import { getFunctions, httpsCallable } from 'firebase/functions';

//create a function we can use to fetch the shops products 
export const getProductsInShop = async (shopid) => {
  try {
    const functions = getFunctions();
    const getProductsFn = httpsCallable(functions, "getProductsInShop");
    const products = await getProductsFn({ shopid });
    const AllProducts = products.docs.map((doc) => ({ id: doc.id, ...doc.data() }));
    return AllProducts;
  } catch (error) {
    console.error("ERROR getting products: ", error);
    return [];
  }
};
//handles the users orders 
export const MyOrders = () => {
  const [orderlist, setorderlist] = useState([]);//holds all the orders from the database
  const currentUserId = localStorage.getItem("userid");
  const currentuserstore = localStorage.getItem("shopname");
  const [productsMap, setProductsMap] = useState([]);
  const [loading, setLoading] = useState(false);
  const [ordersLoading, setOrdersLoading] = useState(true);

  let navigate = useNavigate();
//funciton that goes back to the users shop dash board when triggered
  function navigateDashboard() {
    navigate('/shopdashboard');
  }

  // Get all users orders
  useEffect(() => {
    const fetchOrders = async () => {
      try {
        const functions = getFunctions();
        const getOrders = httpsCallable(functions, 'getOrders');
        const result = await getOrders({});
        setorderlist(result.data.orders);
      } catch (error) {
        console.error('Error fetching orders:', error);
      }finally{
              setOrdersLoading(false);
      }
    };
    
    fetchOrders();
    
  }, []);


  // Get products assosciated with shop ID (autogenerated in firebase, so userID->shopID)
  getProductsInShop(currentUserId);
/*
  const downloadCSVFIle = () => {
    if (sortedProductsBySold.length === 0) return;

    const fields = Object.keys(sortedProductsBySold[0]);
    const csvFields = [
      fields.join(","), // Field rows (according to database)
      ...sortedProductsBySold.map(product => fields.map(field => `"${product[field]}"`).join(","))]; // split each entry onto own line
    //wrap all fields in "...field..." to avoid ambiguity

    const csvFile = csvFields.join("\n");
    const blob = new Blob([csvFile], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "report_trends.csv";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
*/
  // Get all db shops, find this user's shop (userID->shopID), then get its products
  useEffect(() => {
    const fetchUserShopProducts = async () => {
      try {
        const functions = getFunctions();
        const getAllShops = httpsCallable(functions, 'getAllShops');
        const result = await getAllShops({});
        const userShop=(result.data.shops).filter(shop => shop.userid === currentUserId);
        if (userShop.length > 0) {
          const shopId = userShop[0].id; // 1 shop per user
          const products = await getProductsInShop(shopId);
          setProductsMap(products);
        } else {
          console.error("ERROR bcos no shops this user.");
        }
      }
      catch (error) {
        console.error("ERROR getting this shop or products:", error);
      }
    };

    fetchUserShopProducts();
  }, [currentUserId]);

  //IMP: Sort products by sold then by price (display in descending order)
  const sortedProductsBySold = productsMap.sort((a, b) => {
    if (a.sold === b.sold) {
      return b.price - a.price;
    }
    return b.sold - a.sold;
  });

  //filter all the orders rturned by the currentstore name 
  const myorders = orderlist.filter((order) => order.nameofshop === currentuserstore);

  const [orderstatus, setorderstatus] = useState("");
  const [editingOrderid, setEditingOrderid] = useState(null);
//function that updates the order status 
  const updatestatus = async (ordid) => {
     setLoading(true);
    try {
      console.log(orderstatus, ordid);
      const functions = getFunctions();
        const updateOrderStatus = httpsCallable(functions, 'updateOrderStatus');
        await updateOrderStatus({orderStatus:orderstatus, orderId:ordid});
      // Update the local state to reflect the change
      if (orderstatus=="Collected"){
        alert("The order had been removed from Database");
     window.location.reload(); // This refreshes the page to reload the orders if one has bee deleted
        
      }
      else{
      setorderlist(prevOrders => 
        prevOrders.map(order => 
          order.orderid === ordid ? { ...order, status: orderstatus } : order
        )
      );
    }
      setEditingOrderid(null);
      setorderstatus("");
    } catch (err) {
      console.error(err);
    }finally{
       setLoading(false);
    }
  };
  return (


    <section className='Cover'>
      <section className='order-section'>
      <h1>My Orders</h1>
      <button className="back-button" onClick={navigateDashboard}>← Dashboard</button>
      
      {ordersLoading && (
     <section className='loader-wrapper'><section className='loader'> </section></section>)}
     
   {!ordersLoading && myorders.length === 0 && (
  <section className="empty-alert">📭 You have no orders</section>)}
      {loading && <section className="loading-alert">updating status...</section>}
      {myorders.map((ord, index) => (
        <section className="Order" key={index}>
          <h3>Order #{index + 1}</h3>

          {ord.products.map((prod, index2) => (
            <section key={index2}>
              <p><strong>Name:</strong> {prod.nameofitem}</p>
              <p><strong>Quantity:</strong> {prod.quantity}</p>
              <p><strong>Price:</strong>R{prod.price}</p>
            </section>
          ))}

          <p><strong>Address: </strong>{ord.address}</p>

          {ord.orderid === editingOrderid ? (
            <section>
              <select 
                value={orderstatus}
                onChange={(e) => setorderstatus(e.target.value)}
              >
                <option value="" disabled>New Status</option>
                <option value="Ordered">Ordered</option>
                 <option value="Delivery ready">Delivery ready</option>
                <option value="Dispatched">Dispatched</option>
                <option value="Collected">Collected</option>
              </select>
              <button onClick={() => updatestatus(ord.orderid)}>
                Save
              </button>
              <button onClick={() => setEditingOrderid(null)}>
                Cancel
              </button>
            </section>
          ) : (
            <>
            <section className='status-container'>
              <p>
              <strong>Status:</strong> {ord.status}
              </p>
                <button onClick={() => {
                  setEditingOrderid(ord.orderid);
                  setorderstatus(ord.status);
                }}>
                  Update status
                </button>
              </section>
            </>
          )}
        </section>
      ))}

      <section>
        {/*<ul>
          {sortedProductsBySold.map((product) => (
            <p key={product.id}>
              {product.name}, {product.price}, {product.sold}
            </p>
          ))}
        </ul>
        <button onClick={downloadCSVFIle}>Download Trend Report</button>*/}
      </section>
    </section>
    </section>
  );
};
